targets:
  $default:
    sources:
      - lib/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schemas/schema.graphql
              queries_glob: lib/graphql/queries/*.graphql
              output: lib/graphql/api/graphql_api.dart
