name: satni_xml_backend
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
