name: satni_xml_backend
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.1.0
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.16.0
