name: satni_graphql_service
description: A client to query the satni graphql backend
version: 1.0.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  graphql: ^5.1.1
  path: ^1.8.0
  satni_service_interface:
    path: ../satni_service_interface

dev_dependencies:
  build_runner: ^2.2.1
  graphql_codegen: ^0.11.1
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  gql_code_builder: 0.6.0
  gql: 0.13.1
  gql_exec: 0.4.0
