name: satni_service_interface
description: An interface for querying satni backends
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed: ^2.1.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  import_sorter: ^4.6.0
  json_serializable: ^6.4.1
  lints: ^2.0.0
  test: ^1.16.0
