default_platform(:ios)

platform :ios do
  desc "Pre-load distribution certs and profiles"
  lane :match_distribution do
    match(
      type: "appstore",
      readonly: true
    )
    update_project_provisioning(
      xcodeproj: "ios/Runner.xcodeproj",
      profile: ENV["sigh_org.divvun.satni_appstore_profile-path"],
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution"
    )
    update_project_team(
      path: "ios/Runner.xcodeproj",
      teamid: ENV["IOS_TEAM_ID"]
    )
  end
end
