default_platform(:ios)

platform :ios do
  desc "Pre-load distribution certs and profiles"
  lane :match_distribution do
    match(
      type: "appstore",
      readonly: true
    )
    update_project_provisioning(
      xcodeproj: "ios/Runner.xcodeproj",
      profile: ENV["sigh_org.divvun.satni_appstore_profile-path"],
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution"
      # code_signing_identity: "iPhone Distribution"
    )
    update_code_signing_settings(
      path: "ios/Runner.xcodeproj",
      targets: ["Runner"],
      build_configurations: ["Release"],
      code_sign_identity: "Apple Distribution"
    )
    update_project_team(
      path: "ios/Runner.xcodeproj",
      teamid: ENV["IOS_TEAM_ID"]
    )
  end

  desc "Publish the app to the App Store"
  lane :publish do
    match(
      type: "appstore",
      readonly: true
    )
    pilot(
      ipa: "/Users/runner/work/satni_flutter/satni_flutter/build/ios/ipa/Runner.ipa"
    )
  end
end
