name: Main buildchain
on:
  push:
    branches:
      - master
      - dev-ci-*

jobs:
  apk_build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install a JDK
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'zulu'
      #     java-version: '11'
      # - name: Install Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '2.10.2'
      #     channel: 'stable'
      # - name: Disable Google phone-home
      #   run: flutter config --no-analytics
      # - name: Verify flutter version
      #   run: flutter --version
      - name: Install keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 -d > main.jks
      - name: Verify Keystore contents
        run: sha1sum main.jks
      - name: Capture working directory
        id: pwd
        run: echo "::set-output name=wd::$(pwd)"
      - name: Debug the pwd step
        run: echo "${{ toJSON(steps.pwd) }}"
      - name: Build APK
        run: flutter build apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Build AAB
        run: flutter build appbundle
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v2
        with:
          name: aab
          path: build/app/outputs/bundle/release/app-release.aab
